export const FETCH_FILMS_REQUEST = 'FETCH_FILMS_REQUEST'
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS'
export const FETCH_FILMS_FAILURE = 'FETCH_FILMS_FAILURE'

export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE'
